FROM node:10

ARG NEWSAPI__API_KEY
ARG WEBPUSH__PRIVATE_KEY
ARG WEBPUSH__PUBLIC_KEY
ARG MONGODB__USERNAME
ARG MONGODB__PASSWORD

ENV PORT=3000
ENV NEWSAPI__API_KEY=$NEWSAPI__API_KEY
ENV WEBPUSH__PRIVATE_KEY=$WEBPUSH__PRIVATE_KEY
ENV WEBPUSH__PUBLIC_KEY=$WEBPUSH__PUBLIC_KEY
ENV MONGODB__USERNAME=$MONGODB__USERNAME
ENV MONGODB__PASSWORD=$MONGODB__PASSWORD

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build
RUN npm prune --production

EXPOSE 3000

CMD [ "npm", "start" ]
